### ISSUE TITLE
Preconditions to launch the ST test suite are not met

### ISSUE THREAD

**Issue by isabelrios** [mozilla-sensorweb/sensorweb-server#16]
Here are the preconditions for the SenorThing API (STA) 1.0 Test Suite:  http://cite.opengeospatial.org/te2/about/sta10/1.0/site/

According to the previous preconditions, there should be at least one entity per resource. It should be necessary to have data in the DB to test it.

**Comment by ferjm** [comment]
We are already running these tests for mozilla-sensorweb/sensorthings. All that is needed for this repo is to test that the SensorThings routes are correct, and that's already done at https://github.com/mozilla-sensorweb/sensorweb-server/blob/master/test/test_sensorthings_api.js
