### ISSUE TITLE
Form files would be needed to launch the ST Test Suite

### ISSUE THREAD

**Issue by isabelrios** [mozilla-sensorweb/sensorweb-server#17]
Here are some examples of those files  for other Test Suites:
https://github.com/geoserver/geoserver-cite-tools/tree/master/forms

There is nothing for sta10. We would need to create those files to be able to launch the test suite in headless mode.

**Comment by ferjm** [comment]
We are already running these tests for mozilla-sensorweb/sensorthings. All that is needed for this repo is to test that the SensorThings routes are correct, and that's already done at https://github.com/mozilla-sensorweb/sensorweb-server/blob/master/test/test_sensorthings_api.js
