### ISSUE TITLE
Run OGC compliance tests on Travis CI

### ISSUE THREAD

**Issue by ferjm** [mozilla-sensorweb/sensorweb-server#19]

**Comment by isabelrios** [comment]
In order to run the tests on travis it should be possible to run them in headless mode and for that we would need issue #17

**Comment by ferjm** [comment]
We are already running these tests for mozilla-sensorweb/sensorthings. All that is needed for this repo is to test that the SensorThings routes are correct, and that's already done at https://github.com/mozilla-sensorweb/sensorweb-server/blob/master/test/test_sensorthings_api.js
